on:
  workflow_dispatch:

jobs:
  test:
    name: Test module
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: egor-tensin/setup-gcc@v1
    - name: Test module
      run: |
        g++ -fmodules -x c++-system-header -c bits/stdc++.h
        g++ -fmodules -include bits/stdc++.h test.cpp -o test.exe 
        test.exe
