on:
  workflow_dispatch:

jobs:
  test:
    name: Test module
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: egor-tensin/setup-gcc@v1
    - name: Test module
      run: |
        gcc -xc++ -lstdc++ -shared-libgcc -std=c++20 -fmodules -fsearch-include-path bits/std.cc test.cpp -o test.exe 
        test.exe
